package com.czj.mapper;

import com.czj.model.Booktypes;
import com.czj.model.BooktypesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BooktypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    long countByExample(BooktypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    int deleteByExample(BooktypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    int insert(Booktypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    int insertSelective(Booktypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    List<Booktypes> selectByExample(BooktypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    Booktypes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") Booktypes record, @Param("example") BooktypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    int updateByExample(@Param("record") Booktypes record, @Param("example") BooktypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    int updateByPrimaryKeySelective(Booktypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktypes
     *
     * @mbg.generated Sat Jun 30 17:23:41 CST 2018
     */
    int updateByPrimaryKey(Booktypes record);
}